// Generated by scripts/expand_example.py from examples/expansion_demo.rs.
// Full rustc expansion, including pin-project-lite; inspection artifact, not a source module.
#![feature(prelude_import)]
//! Named and anonymous calls performing the same IO; see expanded/expansion_demo.rs.
#![feature(coroutines, coroutine_trait, type_alias_impl_trait)]
extern crate std;
#[prelude_import]
use std::prelude::rust_2024::*;

use nitori_call::{Direct, Target, call, call_closure, run_sync};
use nitori_io::{Read, TargetReadExt, calls::ReadBeError};
use std::{convert::Infallible, pin::Pin};

#[doc(hidden)]
mod __call_read_pair {
    use super::*;
    pub type __State<H: Read> =
        impl ::core::ops::Coroutine<::nitori_call::__private::ResumeContext<H>,
        Yield = __Yield<H>, Return = __Return<H>>;
    #[define_opaque(__State)]
    pub(super) fn make<H: Read>() -> __State<H> {
        ::nitori_call::__private::map_coroutine(::core::convert::identity(#[coroutine] static
                    move
                    |mut __stack_environment:
                        ::nitori_call::__private::ResumeContext<H>|
                    -> Result<u16, ReadBeError<H::Error>>
                    {
                        #[allow(unused_variables)]
                        let io: Target<H> = __stack_environment.target();
                        let first =
                            {
                                    let __await_input = io.read_be::<u8>();
                                    let mut __stack_child =

                                        {
                                            super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                                ::core::pin::PinMacroHelper {
                                                    value: __stack_environment.prepare_await(__await_input),
                                                };
                                            unsafe {
                                                ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                            }
                                        };
                                    loop {
                                        match unsafe {
                                                __stack_environment.poll_await(__stack_child.as_mut())
                                            } {
                                            ::core::task::Poll::Ready(value) => break value,
                                            ::core::task::Poll::Pending => {
                                                __stack_environment.end();
                                                __stack_environment =
                                                    yield ::nitori_call::__private::Suspend::Pending;
                                            }
                                        }
                                    }
                                }?;
                        let second =
                            {
                                    let __await_input = io.read_be::<u8>();
                                    let mut __stack_child =
                                        {
                                            super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                                ::core::pin::PinMacroHelper {
                                                    value: __stack_environment.prepare_await(__await_input),
                                                };
                                            unsafe {
                                                ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                            }
                                        };
                                    loop {
                                        match unsafe {
                                                __stack_environment.poll_await(__stack_child.as_mut())
                                            } {
                                            ::core::task::Poll::Ready(value) => break value,
                                            ::core::task::Poll::Pending => {
                                                __stack_environment.end();
                                                __stack_environment =
                                                    yield ::nitori_call::__private::Suspend::Pending;
                                            }
                                        }
                                    }
                                }?;
                        Ok(u16::from(first) + u16::from(second))
                    }),
            |value| -> __Yield<H>
                { __Yield { value, marker: ::core::marker::PhantomData } },
            |value| -> __Return<H>
                { __Return { value, marker: ::core::marker::PhantomData } })
    }
    pub(super) struct __Return<H: Read> {
        pub(super) value: Result<u16, ReadBeError<H::Error>>,
        marker: ::core::marker::PhantomData<fn() -> __Parameters<H>>,
    }
    pub(super) struct __Yield<H: Read> {
        value: ::nitori_call::__private::Suspend<::core::convert::Infallible>,
        marker: ::core::marker::PhantomData<fn() -> __Parameters<H>>,
    }
    impl<H: Read> ::nitori_call::__private::Suspension for __Yield<H> {
        type Item = ::core::convert::Infallible;
        fn into_suspend(self)
            -> ::nitori_call::__private::Suspend<Self::Item> {
            self.value
        }
    }
    pub struct __Parameters<H: Read> {
        marker: ::core::marker::PhantomData<fn() -> __State<H>>,
    }
    pub(super) struct __Operation<Parameters, Inner> {
        pub(super) inner: Inner,
        pub(super) marker: ::core::marker::PhantomData<fn() -> Parameters>,
    }
    #[allow(explicit_outlives_requirements, single_use_lifetimes, clippy ::
    unknown_clippy_lints, clippy :: absolute_paths, clippy :: min_ident_chars,
    clippy :: redundant_pub_crate, clippy :: single_char_lifetime_names,
    clippy :: used_underscore_binding)]
    const _: () =
        {
            #[doc(hidden)]
            #[allow(dead_code, single_use_lifetimes, clippy ::
            unknown_clippy_lints, clippy :: absolute_paths, clippy ::
            min_ident_chars, clippy :: mut_mut, clippy :: redundant_pub_crate,
            clippy :: ref_option_ref, clippy :: single_char_lifetime_names,
            clippy :: type_repetition_in_bounds)]
            pub(super) struct Projection<'__pin, Parameters, Inner> where
                __Operation<Parameters, Inner>: '__pin {
                pub(super) inner: ::pin_project_lite::__private::Pin<&'__pin mut (Inner)>,
                pub(super) marker: &'__pin mut (::core::marker::PhantomData<fn()
                    -> Parameters>),
            }
            #[doc(hidden)]
            #[allow(dead_code, single_use_lifetimes, clippy ::
            unknown_clippy_lints, clippy :: absolute_paths, clippy ::
            min_ident_chars, clippy :: mut_mut, clippy :: redundant_pub_crate,
            clippy :: ref_option_ref, clippy :: single_char_lifetime_names,
            clippy :: type_repetition_in_bounds)]
            pub(super) struct ProjectionRef<'__pin, Parameters, Inner> where
                __Operation<Parameters, Inner>: '__pin {
                pub(super) inner: ::pin_project_lite::__private::Pin<&'__pin (Inner)>,
                pub(super) marker: &'__pin (::core::marker::PhantomData<fn()
                    -> Parameters>),
            }
            impl<Parameters, Inner> __Operation<Parameters, Inner> {
                #[doc(hidden)]
                #[inline]
                pub(super) fn project<'__pin>(self:
                        ::pin_project_lite::__private::Pin<&'__pin mut Self>)
                    -> Projection<'__pin, Parameters, Inner> {
                    unsafe {
                        let Self { inner, marker } = self.get_unchecked_mut();
                        Projection {
                            inner: ::pin_project_lite::__private::Pin::new_unchecked(inner),
                            marker: marker,
                        }
                    }
                }
                #[doc(hidden)]
                #[inline]
                pub(super) fn project_ref<'__pin>(self:
                        ::pin_project_lite::__private::Pin<&'__pin Self>)
                    -> ProjectionRef<'__pin, Parameters, Inner> {
                    unsafe {
                        let Self { inner, marker } = self.get_ref();
                        ProjectionRef {
                            inner: ::pin_project_lite::__private::Pin::new_unchecked(inner),
                            marker: marker,
                        }
                    }
                }
            }
            #[allow(non_snake_case)]
            pub(super) struct __Origin<'__pin, Parameters, Inner> {
                __dummy_lifetime: ::pin_project_lite::__private::PhantomData<&'__pin ()>,
                inner: Inner,
                marker: ::pin_project_lite::__private::AlwaysUnpin<::core::marker::PhantomData<fn()
                    -> Parameters>>,
            }
            impl<'__pin, Parameters, Inner>
                ::pin_project_lite::__private::Unpin for
                __Operation<Parameters, Inner> where
                ::pin_project_lite::__private::PinnedFieldsOf<__Origin<'__pin,
                Parameters, Inner>>: ::pin_project_lite::__private::Unpin {}
            trait MustNotImplDrop {}
            #[allow(clippy :: drop_bounds, drop_bounds)]
            impl<T: ::pin_project_lite::__private::Drop> MustNotImplDrop for T
                {
            }
            impl<Parameters, Inner> MustNotImplDrop for
                __Operation<Parameters, Inner> {}
            #[forbid(unaligned_references, safe_packed_borrows)]
            fn __assert_not_repr_packed<Parameters,
                Inner>(this: &__Operation<Parameters, Inner>) {
                let _ = &this.inner;
                let _ = &this.marker;
            }
        };
}
type ReadPair<H> =
    __call_read_pair::__Operation<__call_read_pair::__Parameters<H>,
    ::nitori_call::__private::StackCall<H, __call_read_pair::__State<H>>>;
impl<H: Read> ReadPair<H> {
    fn new() -> Self {
        let state = __call_read_pair::make::<H>();
        Self {
            inner: unsafe { ::nitori_call::__private::build_mapped(state) },
            marker: ::core::marker::PhantomData,
        }
    }
}
fn read_pair<H: Read>() -> ReadPair<H> { ReadPair::<H>::new() }
impl<H: Read> ::nitori_call::CallOn<H> for ReadPair<H> {
    type Yield = ::core::convert::Infallible;
    type Return = Result<u16, ReadBeError<H::Error>>;
    #[allow(unreachable_code)]
    fn poll_call<'__visit>(self: ::core::pin::Pin<&mut Self>,
        host:
            ::core::pin::Pin<&mut dyn ::nitori_call::ReceiverScope<'__visit,
            Family = H>>, cx: &mut ::core::task::Context<'_>)
        ->
            ::core::task::Poll<::core::ops::CoroutineState<Self::Yield,
            Self::Return>> where H: '__visit {
        ::nitori_call::CallOn::poll_call(self.project().inner, host,
                cx).map(|event|
                match event {
                    ::core::ops::CoroutineState::Yielded(value) =>
                        ::core::ops::CoroutineState::Yielded(value),
                    ::core::ops::CoroutineState::Complete(value) =>
                        ::core::ops::CoroutineState::Complete(value.value),
                })
    }
}
struct ReadPairArguments<H: Read> {
    __arguments_marker: ::core::marker::PhantomData<fn() -> ReadPair<H>>,
}
impl<H: Read> ReadPairArguments<H> {
    fn new() -> Self {
        Self { __arguments_marker: ::core::marker::PhantomData }
    }
}
impl<H: Read> ::nitori_call::Arguments<H> for ReadPairArguments<H> {
    type Call = ReadPair<H>;
    fn into_call(self) -> Self::Call { <ReadPair<H>>::new() }
}
trait ReadPairExt<H: Read>: ::nitori_call::ResourceDriver<Family = H> {
    fn sync_read_pair<'__call>(self: ::core::pin::Pin<&'__call mut Self>)
        -> <ReadPair<H> as ::nitori_call::CallOn<H>>::Return where
        ReadPair<H>: ::nitori_call::CallOn<H, Yield =
        ::core::convert::Infallible>,
        Self: ::nitori_call::Receiver<Family = H> {
        ::nitori_call::run_sync(self, <ReadPair<H>>::new())
    }
    fn sync_read_pair_unpin<'__call>(&'__call mut self)
        -> <ReadPair<H> as ::nitori_call::CallOn<H>>::Return where
        ReadPair<H>: ::nitori_call::CallOn<H, Yield =
        ::core::convert::Infallible>,
        Self: ::nitori_call::Receiver<Family = H> + Unpin {
        ::nitori_call::run_sync(::core::pin::Pin::new(self),
            <ReadPair<H>>::new())
    }
    fn read_pair<'__call>(self: ::core::pin::Pin<&'__call mut Self>)
        ->
            <Self as
            ::nitori_call::ResourceDriver>::Execution<'__call, ReadPair<H>> {
        ::nitori_call::ResourceDriver::execute(self, <ReadPair<H>>::new())
    }
    fn read_pair_unpin<'__call>(&'__call mut self)
        ->
            <Self as
            ::nitori_call::ResourceDriver>::Execution<'__call, ReadPair<H>>
        where Self: Unpin {
        ::nitori_call::ResourceDriver::execute(::core::pin::Pin::new(self),
            <ReadPair<H>>::new())
    }
}
impl<H: Read, __CallHost: ::nitori_call::ResourceDriver<Family = H> + ?Sized>
    ReadPairExt<H> for __CallHost {}
trait TargetReadPairExt<H: Read>: ::nitori_call::CallTarget<Target = H> +
    Sized {
    fn read_pair(self)
        ->
            ::nitori_call::Child<Self::Root,
            ::nitori_call::AdaptedCall<Self, ReadPair<H>>> {
        ::nitori_call::TargetExt::call(self, <ReadPairArguments<H>>::new())
    }
}
impl<H: Read, __CallReceiver: ::nitori_call::CallTarget<Target = H>>
    TargetReadPairExt<H> for __CallReceiver {}
fn main() {
    let mut input = b"\x01\x02".as_slice();
    {
        match (&input.sync_read_pair_unpin().unwrap(), &3) {
            (left_val, right_val) => {
                if !(*left_val == *right_val) {
                    let kind = ::core::panicking::AssertKind::Eq;
                    ::core::panicking::assert_failed(kind, &*left_val,
                        &*right_val, ::core::option::Option::None);
                }
            }
        }
    };
    if !input.is_empty() {
        ::core::panicking::panic("assertion failed: input.is_empty()")
    };
    let mut input = b"\x01\x02".as_slice();
    let operation =
        {
            let __stack_state =
                ::core::convert::identity(#[coroutine] static
                        |mut __stack_environment:
                            ::nitori_call::__private::ResumeContext<Direct<&[u8]>>|
                        -> Result<u16, ReadBeError<Infallible>>
                        {
                            #[allow(unused_variables)]
                            let io: Target<Direct<&[u8]>> =
                                __stack_environment.target();
                            let first =
                                {
                                        let __await_input = io.read_be::<u8>();
                                        let mut __stack_child =
                                            {
                                                super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                                    ::core::pin::PinMacroHelper {
                                                        value: __stack_environment.prepare_await(__await_input),
                                                    };
                                                unsafe {
                                                    ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                                }
                                            };
                                        loop {
                                            match unsafe {
                                                    __stack_environment.poll_await(__stack_child.as_mut())
                                                } {
                                                ::core::task::Poll::Ready(value) => break value,
                                                ::core::task::Poll::Pending => {
                                                    __stack_environment.end();
                                                    __stack_environment =
                                                        yield ::nitori_call::__private::Suspend::Pending;
                                                }
                                            }
                                        }
                                    }?;
                            let second =
                                {
                                        let __await_input = io.read_be::<u8>();
                                        let mut __stack_child =
                                            {
                                                super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                                    ::core::pin::PinMacroHelper {
                                                        value: __stack_environment.prepare_await(__await_input),
                                                    };
                                                unsafe {
                                                    ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                                }
                                            };
                                        loop {
                                            match unsafe {
                                                    __stack_environment.poll_await(__stack_child.as_mut())
                                                } {
                                                ::core::task::Poll::Ready(value) => break value,
                                                ::core::task::Poll::Pending => {
                                                    __stack_environment.end();
                                                    __stack_environment =
                                                        yield ::nitori_call::__private::Suspend::Pending;
                                                }
                                            }
                                        }
                                    }?;
                            Ok(u16::from(first) + u16::from(second))
                        });
            unsafe {
                ::nitori_call::__private::build::<Direct<&[u8]>, _,
                        ::core::convert::Infallible>(__stack_state)
            }
        };
    {
        match (&run_sync(Pin::new(&mut input), operation).unwrap(), &3) {
            (left_val, right_val) => {
                if !(*left_val == *right_val) {
                    let kind = ::core::panicking::AssertKind::Eq;
                    ::core::panicking::assert_failed(kind, &*left_val,
                        &*right_val, ::core::option::Option::None);
                }
            }
        }
    };
    if !input.is_empty() {
        ::core::panicking::panic("assertion failed: input.is_empty()")
    };
}
