// Generated by scripts/expand_example.py from examples/expansion_demo.rs.
// Full rustc expansion, including pin-project-lite; inspection artifact, not a source module.
#![feature(prelude_import)]
//! Source counterpart of expanded/expansion_demo.rs; both operations do the same work.
#![feature(coroutines, coroutine_trait, type_alias_impl_trait)]
extern crate std;
#[prelude_import]
use std::prelude::rust_2024::*;
use bytes::Bytes;
use nitori_call::CallOn;
use nitori_call::{PollCallExt as _, ReceiverExt as _};
use nitori_call::{call, call_closure};
use nitori_data_frame_codec_example::{
    current_codec::ReceiverReadVarintExt,
    current_codec::{CodecError, ReadSource},
};
use std::{
    future::ready, num::NonZeroUsize, ops::CoroutineState, pin::{Pin, pin},
    task::{Context, Poll, Waker},
};

#[doc(hidden)]
mod __call_read_pair {
    use super::*;
    pub type __State<T: ReadSource> =
        impl ::core::ops::Coroutine<::nitori_call::__private::ResumeEnv<T>,
        Yield = __Yield<T>, Return = __Return<T>>;
    #[define_opaque(__State)]
    pub(super) fn make<T: ReadSource>() -> __State<T> {
        ::nitori_call::__private::map_coroutine(::core::convert::identity(#[coroutine] static
                    move
                    |mut __stack_environment:
                        ::nitori_call::__private::ResumeEnv<T>|
                    -> Result<u64, CodecError>
                    {
                        #[allow(unused_variables)]
                        let io: nitori_call::Receiver<T> =
                            __stack_environment.receiver();
                        let first =
                            {
                                    let __await_input = io.read_varint();
                                    let mut __stack_child =


                                        {
                                            super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                                ::core::pin::PinMacroHelper {
                                                    value: __stack_environment.prepare_await(__await_input),
                                                };
                                            unsafe {
                                                ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                            }
                                        };
                                    loop {
                                        match unsafe {
                                                __stack_environment.poll_await(__stack_child.as_mut())
                                            } {
                                            ::core::task::Poll::Ready(value) => break value,
                                            ::core::task::Poll::Pending => {
                                                __stack_environment.end();
                                                __stack_environment =
                                                    yield ::nitori_call::__private::Suspend::Pending;
                                            }
                                        }
                                    }
                                }?;
                        let first =
                            {
                                let __await_input = io.with(|_| first);
                                let mut __stack_child =
                                    {
                                        super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                            ::core::pin::PinMacroHelper {
                                                value: __stack_environment.prepare_await(__await_input),
                                            };
                                        unsafe {
                                            ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                        }
                                    };
                                loop {
                                    match unsafe {
                                            __stack_environment.poll_await(__stack_child.as_mut())
                                        } {
                                        ::core::task::Poll::Ready(value) => break value,
                                        ::core::task::Poll::Pending => {
                                            __stack_environment.end();
                                            __stack_environment =
                                                yield ::nitori_call::__private::Suspend::Pending;
                                        }
                                    }
                                }
                            };
                        let offset =
                            {
                                let __await_input = ready(0u64);
                                let mut __stack_child =
                                    {
                                        super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                            ::core::pin::PinMacroHelper {
                                                value: __stack_environment.prepare_await(__await_input),
                                            };
                                        unsafe {
                                            ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                        }
                                    };
                                loop {
                                    match unsafe {
                                            __stack_environment.poll_await(__stack_child.as_mut())
                                        } {
                                        ::core::task::Poll::Ready(value) => break value,
                                        ::core::task::Poll::Pending => {
                                            __stack_environment.end();
                                            __stack_environment =
                                                yield ::nitori_call::__private::Suspend::Pending;
                                        }
                                    }
                                }
                            };
                        {
                            let __stack_item = first;
                            __stack_environment.end();
                            __stack_environment =
                                yield ::nitori_call::__private::Suspend::Emit(__stack_item);
                        };
                        Ok(first +
                                    {
                                            let __await_input = io.read_varint();
                                            let mut __stack_child =
                                                {
                                                    super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                                        ::core::pin::PinMacroHelper {
                                                            value: __stack_environment.prepare_await(__await_input),
                                                        };
                                                    unsafe {
                                                        ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                                    }
                                                };
                                            loop {
                                                match unsafe {
                                                        __stack_environment.poll_await(__stack_child.as_mut())
                                                    } {
                                                    ::core::task::Poll::Ready(value) => break value,
                                                    ::core::task::Poll::Pending => {
                                                        __stack_environment.end();
                                                        __stack_environment =
                                                            yield ::nitori_call::__private::Suspend::Pending;
                                                    }
                                                }
                                            }
                                        }? + offset)
                    }),
            |value| -> __Yield<T>
                { __Yield { value, marker: ::core::marker::PhantomData } },
            |value| -> __Return<T>
                { __Return { value, marker: ::core::marker::PhantomData } })
    }
    pub(super) struct __Return<T: ReadSource> {
        pub(super) value: Result<u64, CodecError>,
        marker: ::core::marker::PhantomData<fn() -> __Parameters<T>>,
    }
    pub(super) struct __Yield<T: ReadSource> {
        value: ::nitori_call::__private::Suspend<u64>,
        marker: ::core::marker::PhantomData<fn() -> __Parameters<T>>,
    }
    impl<T: ReadSource> ::nitori_call::__private::Suspension for __Yield<T> {
        type Item = u64;
        fn into_suspend(self)
            -> ::nitori_call::__private::Suspend<Self::Item> {
            self.value
        }
    }
    pub struct __Parameters<T: ReadSource> {
        marker: ::core::marker::PhantomData<fn() -> __State<T>>,
    }
    pub(super) struct __Operation<Parameters, Inner> {
        pub(super) inner: Inner,
        pub(super) marker: ::core::marker::PhantomData<fn() -> Parameters>,
    }
    #[allow(explicit_outlives_requirements, single_use_lifetimes, clippy ::
    unknown_clippy_lints, clippy :: absolute_paths, clippy :: min_ident_chars,
    clippy :: redundant_pub_crate, clippy :: single_char_lifetime_names,
    clippy :: used_underscore_binding)]
    const _: () =
        {
            #[doc(hidden)]
            #[allow(dead_code, single_use_lifetimes, clippy ::
            unknown_clippy_lints, clippy :: absolute_paths, clippy ::
            min_ident_chars, clippy :: mut_mut, clippy :: redundant_pub_crate,
            clippy :: ref_option_ref, clippy :: single_char_lifetime_names,
            clippy :: type_repetition_in_bounds)]
            pub(super) struct Projection<'__pin, Parameters, Inner> where
                __Operation<Parameters, Inner>: '__pin {
                pub(super) inner: ::pin_project_lite::__private::Pin<&'__pin mut (Inner)>,
                pub(super) marker: &'__pin mut (::core::marker::PhantomData<fn()
                    -> Parameters>),
            }
            #[doc(hidden)]
            #[allow(dead_code, single_use_lifetimes, clippy ::
            unknown_clippy_lints, clippy :: absolute_paths, clippy ::
            min_ident_chars, clippy :: mut_mut, clippy :: redundant_pub_crate,
            clippy :: ref_option_ref, clippy :: single_char_lifetime_names,
            clippy :: type_repetition_in_bounds)]
            pub(super) struct ProjectionRef<'__pin, Parameters, Inner> where
                __Operation<Parameters, Inner>: '__pin {
                pub(super) inner: ::pin_project_lite::__private::Pin<&'__pin (Inner)>,
                pub(super) marker: &'__pin (::core::marker::PhantomData<fn()
                    -> Parameters>),
            }
            impl<Parameters, Inner> __Operation<Parameters, Inner> {
                #[doc(hidden)]
                #[inline]
                pub(super) fn project<'__pin>(self:
                        ::pin_project_lite::__private::Pin<&'__pin mut Self>)
                    -> Projection<'__pin, Parameters, Inner> {
                    unsafe {
                        let Self { inner, marker } = self.get_unchecked_mut();
                        Projection {
                            inner: ::pin_project_lite::__private::Pin::new_unchecked(inner),
                            marker: marker,
                        }
                    }
                }
                #[doc(hidden)]
                #[inline]
                pub(super) fn project_ref<'__pin>(self:
                        ::pin_project_lite::__private::Pin<&'__pin Self>)
                    -> ProjectionRef<'__pin, Parameters, Inner> {
                    unsafe {
                        let Self { inner, marker } = self.get_ref();
                        ProjectionRef {
                            inner: ::pin_project_lite::__private::Pin::new_unchecked(inner),
                            marker: marker,
                        }
                    }
                }
            }
            #[allow(non_snake_case)]
            pub(super) struct __Origin<'__pin, Parameters, Inner> {
                __dummy_lifetime: ::pin_project_lite::__private::PhantomData<&'__pin ()>,
                inner: Inner,
                marker: ::pin_project_lite::__private::AlwaysUnpin<::core::marker::PhantomData<fn()
                    -> Parameters>>,
            }
            impl<'__pin, Parameters, Inner>
                ::pin_project_lite::__private::Unpin for
                __Operation<Parameters, Inner> where
                ::pin_project_lite::__private::PinnedFieldsOf<__Origin<'__pin,
                Parameters, Inner>>: ::pin_project_lite::__private::Unpin {}
            trait MustNotImplDrop {}
            #[allow(clippy :: drop_bounds, drop_bounds)]
            impl<T: ::pin_project_lite::__private::Drop> MustNotImplDrop for T
                {
            }
            impl<Parameters, Inner> MustNotImplDrop for
                __Operation<Parameters, Inner> {}
            #[forbid(unaligned_references, safe_packed_borrows)]
            fn __assert_not_repr_packed<Parameters,
                Inner>(this: &__Operation<Parameters, Inner>) {
                let _ = &this.inner;
                let _ = &this.marker;
            }
        };
}
type ReadPair<T> =
    __call_read_pair::__Operation<__call_read_pair::__Parameters<T>,
    ::nitori_call::__private::StackCall<T, __call_read_pair::__State<T>>>;
impl<T: ReadSource> ReadPair<T> {
    fn new() -> Self {
        let state = __call_read_pair::make::<T>();
        Self {
            inner: unsafe { ::nitori_call::__private::build_mapped(state) },
            marker: ::core::marker::PhantomData,
        }
    }
}
fn read_pair<T: ReadSource>() -> ReadPair<T> { ReadPair::<T>::new() }
impl<T: ReadSource> ::nitori_call::CallOn<T> for ReadPair<T> {
    type Yield = u64;
    type Return = Result<u64, CodecError>;
    #[allow(unreachable_code)]
    fn poll_call<'__visit>(self: ::core::pin::Pin<&mut Self>,
        host:
            ::core::pin::Pin<&mut <T as
            ::nitori_call::HostFamily>::Host<'__visit>>,
        cx: &mut ::core::task::Context<'_>)
        ->
            ::core::task::Poll<::core::ops::CoroutineState<Self::Yield,
            Self::Return>> where T: '__visit {
        ::nitori_call::CallOn::poll_call(self.project().inner, host,
                cx).map(|event|
                match event {
                    ::core::ops::CoroutineState::Yielded(value) =>
                        ::core::ops::CoroutineState::Yielded(value),
                    ::core::ops::CoroutineState::Complete(value) =>
                        ::core::ops::CoroutineState::Complete(value.value),
                })
    }
}
struct ReadPairArguments<T: ReadSource> {
    __arguments_marker: ::core::marker::PhantomData<fn() -> ReadPair<T>>,
}
impl<T: ReadSource> ReadPairArguments<T> {
    fn new() -> Self {
        Self { __arguments_marker: ::core::marker::PhantomData }
    }
}
impl<T: ReadSource> ::nitori_call::Arguments<T> for ReadPairArguments<T> {
    type Call = ReadPair<T>;
    fn into_call(self) -> Self::Call { <ReadPair<T>>::new() }
}
trait ReadPairExt<T: ReadSource>: ::nitori_call::Host<Family = T> {
    fn read_pair<'__call>(self: ::core::pin::Pin<&'__call mut Self>)
        -> ::nitori_call::BoundCall<'__call, Self, ReadPair<T>> {
        ::nitori_call::BoundCall::new(self, <ReadPair<T>>::new())
    }
    fn read_pair_unpin<'__call>(&'__call mut self)
        -> ::nitori_call::BoundCall<'__call, Self, ReadPair<T>> where
        Self: Unpin {
        ::nitori_call::BoundCall::new(::core::pin::Pin::new(self),
            <ReadPair<T>>::new())
    }
}
impl<T: ReadSource, __CallHost: ::nitori_call::Host<Family = T> + ?Sized>
    ReadPairExt<T> for __CallHost {}
trait ReceiverReadPairExt<T: ReadSource>: ::nitori_call::CallReceiver<Target =
    T> + Sized {
    fn read_pair(self)
        ->
            ::nitori_call::Child<Self::Root,
            ::nitori_call::ReceivedCall<Self, ReadPair<T>>> {
        ::nitori_call::ReceiverExt::call(self, <ReadPairArguments<T>>::new())
    }
}
impl<T: ReadSource, __CallReceiver: ::nitori_call::CallReceiver<Target = T>>
    ReceiverReadPairExt<T> for __CallReceiver {}
struct Source(Bytes);
impl ReadSource for Source {
    fn poll_read<'visit>(host: Pin<&mut Self::Host<'visit>>,
        maximum: NonZeroUsize, _: &mut Context<'_>)
        -> Poll<Result<Option<Bytes>, CodecError>> where Self: 'visit {
        let mut this = host.get_mut().0.as_mut();
        let count = this.0.len().min(maximum.get());
        Poll::Ready(Ok(if count == 0 {
                    None
                } else { Some(this.0.split_to(count)) }))
    }
}
fn check<Operation>(operation: Operation) where
    Operation: CallOn<Source, Yield = u64, Return = Result<u64, CodecError>> {
    let mut operation =
        {
            super let mut pinned: ::core::pin::PinMacroHelper<_> =
                ::core::pin::PinMacroHelper { value: operation };
            unsafe { ::core::pin::pin_new_unchecked_in_helper(&mut pinned) }
        };
    let mut source = Source(Bytes::from_static(b"\x01\x02"));
    let mut cx = Context::from_waker(Waker::noop());
    if !#[allow(non_exhaustive_omitted_patterns)] match operation.as_mut().poll_host(Pin::new(&mut source),
                    &mut cx) {
                Poll::Ready(CoroutineState::Yielded(1)) => true,
                _ => false,
            } {
        ::core::panicking::panic("assertion failed: matches!(operation.as_mut().poll_host(Pin::new(&mut source), &mut cx),\n    Poll::Ready(CoroutineState::Yielded(1)))")
    };
    {
        match (&source.0.as_ref(), &b"\x02") {
            (left_val, right_val) => {
                if !(*left_val == *right_val) {
                    let kind = ::core::panicking::AssertKind::Eq;
                    ::core::panicking::assert_failed(kind, &*left_val,
                        &*right_val, ::core::option::Option::None);
                }
            }
        }
    };
    if !#[allow(non_exhaustive_omitted_patterns)] match operation.as_mut().poll_host(Pin::new(&mut source),
                    &mut cx) {
                Poll::Ready(CoroutineState::Complete(Ok(3))) => true,
                _ => false,
            } {
        ::core::panicking::panic("assertion failed: matches!(operation.as_mut().poll_host(Pin::new(&mut source), &mut cx),\n    Poll::Ready(CoroutineState::Complete(Ok(3))))")
    };
    if !source.0.is_empty() {
        ::core::panicking::panic("assertion failed: source.0.is_empty()")
    };
}
fn main() {
    check(read_pair());
    check({
            let __stack_state =
                ::core::convert::identity(#[coroutine] static
                        |mut __stack_environment:
                            ::nitori_call::__private::ResumeEnv<Source>|
                        -> Result<u64, CodecError>
                        {
                            #[allow(unused_variables)]
                            let io: nitori_call::Receiver<Source> =
                                __stack_environment.receiver();
                            let first =
                                {
                                        let __await_input = io.read_varint();
                                        let mut __stack_child =
                                            {
                                                super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                                    ::core::pin::PinMacroHelper {
                                                        value: __stack_environment.prepare_await(__await_input),
                                                    };
                                                unsafe {
                                                    ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                                }
                                            };
                                        loop {
                                            match unsafe {
                                                    __stack_environment.poll_await(__stack_child.as_mut())
                                                } {
                                                ::core::task::Poll::Ready(value) => break value,
                                                ::core::task::Poll::Pending => {
                                                    __stack_environment.end();
                                                    __stack_environment =
                                                        yield ::nitori_call::__private::Suspend::Pending;
                                                }
                                            }
                                        }
                                    }?;
                            let first =
                                {
                                    let __await_input = io.with(|_| first);
                                    let mut __stack_child =
                                        {
                                            super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                                ::core::pin::PinMacroHelper {
                                                    value: __stack_environment.prepare_await(__await_input),
                                                };
                                            unsafe {
                                                ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                            }
                                        };
                                    loop {
                                        match unsafe {
                                                __stack_environment.poll_await(__stack_child.as_mut())
                                            } {
                                            ::core::task::Poll::Ready(value) => break value,
                                            ::core::task::Poll::Pending => {
                                                __stack_environment.end();
                                                __stack_environment =
                                                    yield ::nitori_call::__private::Suspend::Pending;
                                            }
                                        }
                                    }
                                };
                            let offset =
                                {
                                    let __await_input = ready(0u64);
                                    let mut __stack_child =
                                        {
                                            super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                                ::core::pin::PinMacroHelper {
                                                    value: __stack_environment.prepare_await(__await_input),
                                                };
                                            unsafe {
                                                ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                            }
                                        };
                                    loop {
                                        match unsafe {
                                                __stack_environment.poll_await(__stack_child.as_mut())
                                            } {
                                            ::core::task::Poll::Ready(value) => break value,
                                            ::core::task::Poll::Pending => {
                                                __stack_environment.end();
                                                __stack_environment =
                                                    yield ::nitori_call::__private::Suspend::Pending;
                                            }
                                        }
                                    }
                                };
                            {
                                let __stack_item = first;
                                __stack_environment.end();
                                __stack_environment =
                                    yield ::nitori_call::__private::Suspend::Emit(__stack_item);
                            };
                            Ok(first +
                                        {
                                                let __await_input = io.read_varint();
                                                let mut __stack_child =
                                                    {
                                                        super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                                            ::core::pin::PinMacroHelper {
                                                                value: __stack_environment.prepare_await(__await_input),
                                                            };
                                                        unsafe {
                                                            ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                                        }
                                                    };
                                                loop {
                                                    match unsafe {
                                                            __stack_environment.poll_await(__stack_child.as_mut())
                                                        } {
                                                        ::core::task::Poll::Ready(value) => break value,
                                                        ::core::task::Poll::Pending => {
                                                            __stack_environment.end();
                                                            __stack_environment =
                                                                yield ::nitori_call::__private::Suspend::Pending;
                                                        }
                                                    }
                                                }
                                            }? + offset)
                        });
            unsafe {
                ::nitori_call::__private::build::<Source, _, _>(__stack_state)
            }
        });
}
impl ::nitori_call::HostFamily for Source {
    type Host<'visit> = ::nitori_call::BorrowedHost<'visit, Self> where
        Self: 'visit;
}
impl ::nitori_call::Host for Source {
    type Family = Self;
    fn view<'visit>(self: ::core::pin::Pin<&'visit mut Self>)
        -> ::nitori_call::BorrowedHost<'visit, Self> where Self: 'visit {
        ::nitori_call::BorrowedHost(self)
    }
}
