// Generated by scripts/expand_example.py from examples/expansion_demo.rs.
// Full rustc expansion, including pin-project; inspection artifact, not a source module.
#![feature(prelude_import)]
//! Source counterpart of expanded/expansion_demo.rs; both operations do the same work.
#![feature(coroutines, coroutine_trait, type_alias_impl_trait)]
extern crate std;
#[prelude_import]
use std::prelude::rust_2024::*;
use bytes::Bytes;
use nitori_call::CallOn;
use nitori_call::{call, call_closure};
use nitori_data_frame_codec_example::{
    current_codec::ReadVarint, current_codec::{CodecError, ReadSource},
};
use std::{
    future::ready, num::NonZeroUsize, ops::CoroutineState, pin::{Pin, pin},
    task::{Context, Poll, Waker},
};

#[doc(hidden)]
mod __call_read_pair {
    use super::*;
    pub type State<T: ReadSource + ?Sized> =
        impl ::core::ops::Coroutine<::nitori_call::__private::ResumeEnv<T>,
        Yield = ::nitori_call::__private::Suspend<u64>, Return =
        Result<u64, CodecError>>;
    #[define_opaque(State)]
    pub(super) fn make<T: ReadSource + ?Sized>() -> State<T> {
        ::core::convert::identity(#[coroutine] static move
                |mut __stack_environment:
                    ::nitori_call::__private::ResumeEnv<T>|
                -> Result<u64, CodecError>
                {
                    let first =
                        {
                                let mut __stack_child =

                                    {
                                        super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                            ::core::pin::PinMacroHelper { value: ReadVarint::new() };
                                        unsafe {
                                            ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                        }
                                    };
                                loop {
                                    match unsafe {
                                            __stack_environment.poll_complete(__stack_child.as_mut())
                                        } {
                                        ::core::task::Poll::Ready(value) => break value,
                                        ::core::task::Poll::Pending => {
                                            __stack_environment.end();
                                            __stack_environment =
                                                yield ::nitori_call::__private::Suspend::Pending;
                                        }
                                    }
                                }
                            }?;
                    let first =
                        {
                            let __stack_callback =
                                ::nitori_call::__private::prepare::<T, _, _>(|_| first);
                            unsafe { __stack_environment.with(__stack_callback) }
                        };
                    let offset =
                        {
                            let mut __stack_child =
                                {
                                    super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                        ::core::pin::PinMacroHelper {
                                            value: ::core::future::IntoFuture::into_future(ready(0u64)),
                                        };
                                    unsafe {
                                        ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                    }
                                };
                            loop {
                                match unsafe {
                                        __stack_environment.poll_future(__stack_child.as_mut())
                                    } {
                                    ::core::task::Poll::Ready(value) => break value,
                                    ::core::task::Poll::Pending => {
                                        __stack_environment.end();
                                        __stack_environment =
                                            yield ::nitori_call::__private::Suspend::Pending;
                                    }
                                }
                            }
                        };
                    {
                        let __stack_item = first;
                        __stack_environment.end();
                        __stack_environment =
                            yield ::nitori_call::__private::Suspend::Emit(__stack_item);
                    };
                    Ok(first +
                                {
                                        let mut __stack_child =
                                            {
                                                super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                                    ::core::pin::PinMacroHelper { value: ReadVarint::new() };
                                                unsafe {
                                                    ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                                }
                                            };
                                        loop {
                                            match unsafe {
                                                    __stack_environment.poll_complete(__stack_child.as_mut())
                                                } {
                                                ::core::task::Poll::Ready(value) => break value,
                                                ::core::task::Poll::Pending => {
                                                    __stack_environment.end();
                                                    __stack_environment =
                                                        yield ::nitori_call::__private::Suspend::Pending;
                                                }
                                            }
                                        }
                                    }? + offset)
                })
    }
}
#[pin(__private())]
struct ReadPair<T: ReadSource + ?Sized> {
    #[pin]
    inner: ::nitori_call::__private::StackCall<T, __call_read_pair::State<T>>,
}
#[allow(unused_qualifications, deprecated, explicit_outlives_requirements,
single_use_lifetimes, unreachable_pub, unused_tuple_struct_fields, clippy ::
unknown_clippy_lints, clippy :: absolute_paths, clippy :: min_ident_chars,
clippy :: pattern_type_mismatch, clippy :: pub_with_shorthand, clippy ::
redundant_pub_crate, clippy :: single_char_lifetime_names, clippy ::
type_repetition_in_bounds, clippy :: elidable_lifetime_names, clippy ::
missing_const_for_fn, clippy :: needless_lifetimes, clippy ::
semicolon_if_nothing_returned, clippy :: use_self, clippy ::
used_underscore_binding)]
const _: () =
    {
        #[allow(unused_extern_crates)]
        extern crate pin_project as _pin_project;
        #[allow(dead_code, clippy :: missing_docs_in_private_items, clippy ::
        mut_mut)]
        struct __ReadPairProjection<'pin, T: ReadSource + ?Sized> where
            ReadPair<T>: 'pin {
            inner: ::pin_project::__private::Pin<&'pin mut (::nitori_call::__private::StackCall<T,
            __call_read_pair::State<T>>)>,
        }
        #[allow(dead_code, clippy :: missing_docs_in_private_items, clippy ::
        ref_option_ref)]
        struct __ReadPairProjectionRef<'pin, T: ReadSource + ?Sized> where
            ReadPair<T>: 'pin {
            inner: ::pin_project::__private::Pin<&'pin (::nitori_call::__private::StackCall<T,
            __call_read_pair::State<T>>)>,
        }
        impl<T: ReadSource + ?Sized> ReadPair<T> {
            #[allow(dead_code)]
            #[inline]
            fn project<'pin>(self:
                    _pin_project::__private::Pin<&'pin mut Self>)
                -> __ReadPairProjection<'pin, T> {
                unsafe {
                    let Self { inner } = self.get_unchecked_mut();
                    __ReadPairProjection {
                        inner: _pin_project::__private::Pin::new_unchecked(inner),
                    }
                }
            }
            #[allow(dead_code)]
            #[inline]
            fn project_ref<'pin>(self:
                    _pin_project::__private::Pin<&'pin Self>)
                -> __ReadPairProjectionRef<'pin, T> {
                unsafe {
                    let Self { inner } = self.get_ref();
                    __ReadPairProjectionRef {
                        inner: _pin_project::__private::Pin::new_unchecked(inner),
                    }
                }
            }
        }
        #[forbid(unaligned_references, safe_packed_borrows)]
        fn __assert_not_repr_packed<T: ReadSource +
            ?Sized>(this: &ReadPair<T>) {
            let _ = &this.inner;
        }
        #[allow(missing_debug_implementations, unnameable_types)]
        struct __ReadPair<'pin, T: ReadSource + ?Sized> {
            __pin_project_use_generics: _pin_project::__private::AlwaysUnpin<'pin,
            (_pin_project::__private::PhantomData<T>)>,
            __field0: ::nitori_call::__private::StackCall<T,
            __call_read_pair::State<T>>,
        }
        impl<'pin, T: ReadSource + ?Sized> _pin_project::__private::Unpin for
            ReadPair<T> where
            _pin_project::__private::PinnedFieldsOf<__ReadPair<'pin,
            T>>: _pin_project::__private::Unpin {}
        #[doc(hidden)]
        unsafe impl<'pin, T: ReadSource + ?Sized> _pin_project::UnsafeUnpin
            for ReadPair<T> where
            _pin_project::__private::PinnedFieldsOf<__ReadPair<'pin,
            T>>: _pin_project::__private::Unpin {
        }
        trait ReadPairMustNotImplDrop {}
        #[allow(clippy :: drop_bounds, drop_bounds)]
        impl<T: _pin_project::__private::Drop> ReadPairMustNotImplDrop for T {
        }
        impl<T: ReadSource + ?Sized> ReadPairMustNotImplDrop for ReadPair<T>
            {}
        #[doc(hidden)]
        impl<T: ReadSource + ?Sized> _pin_project::__private::PinnedDrop for
            ReadPair<T> {
            unsafe fn drop(self: _pin_project::__private::Pin<&mut Self>) {}
        }
    };
impl<T: ReadSource + ?Sized> ReadPair<T> {
    fn new() -> Self {
        let state = __call_read_pair::make::<T>();
        Self { inner: unsafe { ::nitori_call::__private::build(state) } }
    }
}
fn read_pair<T: ReadSource + ?Sized>() -> ReadPair<T> { ReadPair::<T>::new() }
impl<T: ReadSource + ?Sized> ::nitori_call::CallOn<T> for ReadPair<T> {
    type Yield = u64;
    type Return = Result<u64, CodecError>;
    fn poll_call(self: ::core::pin::Pin<&mut Self>,
        host: ::core::pin::Pin<&mut T>, cx: &mut ::core::task::Context<'_>)
        ->
            ::core::task::Poll<::core::ops::CoroutineState<Self::Yield,
            Self::Return>> {
        ::nitori_call::CallOn::poll_call(self.project().inner, host, cx)
    }
}
trait ReadPairExt where Self: ReadSource,
    ReadPair<Self>: ::nitori_call::CallOn<Self> {
    fn read_pair<'__call_host>(self: ::core::pin::Pin<&'__call_host mut Self>)
        -> ::nitori_call::BoundCall<'__call_host, Self, ReadPair<Self>> {
        ::nitori_call::BoundCall::new(self, <ReadPair<Self>>::new())
    }
    fn read_pair_unpin<'__call_host>(&'__call_host mut self)
        -> ::nitori_call::BoundCall<'__call_host, Self, ReadPair<Self>> where
        Self: ::core::marker::Unpin {
        ::nitori_call::BoundCall::new(::core::pin::Pin::new(self),
            <ReadPair<Self>>::new())
    }
}
impl<__CallHost: ?Sized> ReadPairExt for __CallHost where
    __CallHost: ReadSource,
    ReadPair<__CallHost>: ::nitori_call::CallOn<__CallHost> {}
struct Source(Bytes);
impl ReadSource for Source {
    fn poll_read(mut self: Pin<&mut Self>, maximum: NonZeroUsize,
        _: &mut Context<'_>) -> Poll<Result<Option<Bytes>, CodecError>> {
        let count = self.0.len().min(maximum.get());
        Poll::Ready(Ok(if count == 0 {
                    None
                } else { Some(self.0.split_to(count)) }))
    }
}
fn check<Operation>(operation: Operation) where
    Operation: CallOn<Source, Yield = u64, Return = Result<u64, CodecError>> {
    let mut operation =
        {
            super let mut pinned: ::core::pin::PinMacroHelper<_> =
                ::core::pin::PinMacroHelper { value: operation };
            unsafe { ::core::pin::pin_new_unchecked_in_helper(&mut pinned) }
        };
    let mut source = Source(Bytes::from_static(b"\x01\x02"));
    let mut cx = Context::from_waker(Waker::noop());
    if !#[allow(non_exhaustive_omitted_patterns)] match operation.as_mut().poll_call(Pin::new(&mut source),
                    &mut cx) {
                Poll::Ready(CoroutineState::Yielded(1)) => true,
                _ => false,
            } {
        ::core::panicking::panic("assertion failed: matches!(operation.as_mut().poll_call(Pin::new(&mut source), &mut cx),\n    Poll::Ready(CoroutineState::Yielded(1)))")
    };
    {
        match (&source.0.as_ref(), &b"\x02") {
            (left_val, right_val) => {
                if !(*left_val == *right_val) {
                    let kind = ::core::panicking::AssertKind::Eq;
                    ::core::panicking::assert_failed(kind, &*left_val,
                        &*right_val, ::core::option::Option::None);
                }
            }
        }
    };
    if !#[allow(non_exhaustive_omitted_patterns)] match operation.as_mut().poll_call(Pin::new(&mut source),
                    &mut cx) {
                Poll::Ready(CoroutineState::Complete(Ok(3))) => true,
                _ => false,
            } {
        ::core::panicking::panic("assertion failed: matches!(operation.as_mut().poll_call(Pin::new(&mut source), &mut cx),\n    Poll::Ready(CoroutineState::Complete(Ok(3))))")
    };
    if !source.0.is_empty() {
        ::core::panicking::panic("assertion failed: source.0.is_empty()")
    };
}
fn main() {
    check(read_pair());
    check({
            let __stack_state =
                ::core::convert::identity(#[coroutine] static
                        |mut __stack_environment:
                            ::nitori_call::__private::ResumeEnv<Source>|
                        -> Result<u64, CodecError>
                        {
                            let first =
                                {
                                        let mut __stack_child =
                                            {
                                                super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                                    ::core::pin::PinMacroHelper { value: ReadVarint::new() };
                                                unsafe {
                                                    ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                                }
                                            };
                                        loop {
                                            match unsafe {
                                                    __stack_environment.poll_complete(__stack_child.as_mut())
                                                } {
                                                ::core::task::Poll::Ready(value) => break value,
                                                ::core::task::Poll::Pending => {
                                                    __stack_environment.end();
                                                    __stack_environment =
                                                        yield ::nitori_call::__private::Suspend::Pending;
                                                }
                                            }
                                        }
                                    }?;
                            let first =
                                {
                                    let __stack_callback =
                                        ::nitori_call::__private::prepare::<Source, _,
                                                _>(|_| first);
                                    unsafe { __stack_environment.with(__stack_callback) }
                                };
                            let offset =
                                {
                                    let mut __stack_child =
                                        {
                                            super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                                ::core::pin::PinMacroHelper {
                                                    value: ::core::future::IntoFuture::into_future(ready(0u64)),
                                                };
                                            unsafe {
                                                ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                            }
                                        };
                                    loop {
                                        match unsafe {
                                                __stack_environment.poll_future(__stack_child.as_mut())
                                            } {
                                            ::core::task::Poll::Ready(value) => break value,
                                            ::core::task::Poll::Pending => {
                                                __stack_environment.end();
                                                __stack_environment =
                                                    yield ::nitori_call::__private::Suspend::Pending;
                                            }
                                        }
                                    }
                                };
                            {
                                let __stack_item = first;
                                __stack_environment.end();
                                __stack_environment =
                                    yield ::nitori_call::__private::Suspend::Emit(__stack_item);
                            };
                            Ok(first +
                                        {
                                                let mut __stack_child =
                                                    {
                                                        super let mut pinned: ::core::pin::PinMacroHelper<_> =
                                                            ::core::pin::PinMacroHelper { value: ReadVarint::new() };
                                                        unsafe {
                                                            ::core::pin::pin_new_unchecked_in_helper(&mut pinned)
                                                        }
                                                    };
                                                loop {
                                                    match unsafe {
                                                            __stack_environment.poll_complete(__stack_child.as_mut())
                                                        } {
                                                        ::core::task::Poll::Ready(value) => break value,
                                                        ::core::task::Poll::Pending => {
                                                            __stack_environment.end();
                                                            __stack_environment =
                                                                yield ::nitori_call::__private::Suspend::Pending;
                                                        }
                                                    }
                                                }
                                            }? + offset)
                        });
            unsafe {
                ::nitori_call::__private::build::<Source, _, _>(__stack_state)
            }
        });
}
