#!/usr/bin/env python3
"""Save rustc's complete expansion of both public macro forms for inspection."""
from pathlib import Path
import subprocess

root = Path(__file__).resolve().parents[1]
result = subprocess.run(
    ["cargo", "rustc", "--locked", "--example", "expansion_demo", "--", "-Zunpretty=expanded"],
    cwd=root, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
)
if result.returncode:
    raise SystemExit(result.stderr)
destination = root / "expanded" / "expansion_demo.rs"
destination.parent.mkdir(exist_ok=True)
destination.write_text(
    "// Generated by scripts/expand_example.py from examples/expansion_demo.rs.\n"
    "// Full rustc expansion, including pin-project-lite; inspection artifact, not a source module.\n"
    + result.stdout
)
print(f"wrote {destination.relative_to(root)}")
